### ISSUE TITLE
 libboost_regex-mt.dll was not  was not found

### ISSUE THREAD

**Issue by SalmaTofaily** [hlthi/audiowaveform-windows#2]
I tried it on windows 10
I got this error:
The code execution cannot proceed because libboost_regex-mt.dll was not  was not found

**Comment by hlthi** [comment]
I don't use windows anymore. But I think you need install libboost_regex-mt.dll manually on your computer. 

[Link1](https://code.google.com/archive/p/freehal/source/default/source ) and [Link2](https://github.com/kirushyk/kms-windows/tree/master/bin )  have libboost_regex-mt.dll file.
[Thats](https://www.quora.com/How-do-I-register-DLL-files-in-a-Windows-10-64-bit) how to load a dll on your windows os.

Note : Link1's size and Link2's size different from each other so you should take responsibility for yourself.
